services:
  microservice:
    image: node:21.7.3 
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install --no-audit && npm run dev"
  gateway:
    image: node:21.7.3
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install --no-audit && npm run dev"

networks:
  msexample:
    driver: bridge